/* Simulated frame source.
 *
 * Replays the frames in sim_frames.h, which are generated by
 * test/tools/gen_vectors.py from the same definitions as the host test
 * vectors. No frame bytes are hand-written, so the simulated path cannot
 * drift away from the tested one.
 *
 * This exists so the app is verifiable on real hardware before the SX1262
 * arrives. It is not a stub to be deleted later: keeping it means the UI and
 * decode path stay testable without a radio, which is useful whenever the
 * radio itself is the suspect. */
#ifndef SOURCE_SIM_H
#define SOURCE_SIM_H

#include "src/radio/frame_source.h"

/* interval_ms is how long poll() waits before producing the next frame. */
FrameSource* source_sim_alloc(uint32_t interval_ms);
void source_sim_free(FrameSource* source);

#endif
