#!/usr/bin/env python3
"""Generate host test vectors for the Meshtastic receive path.

Independence is the point. AES comes from OpenSSL via `cryptography`, and the
Data protobuf comes from the real meshtastic package, so a shared
misunderstanding between the generator and the C code cannot quietly pass.

Run from the repo root:
    python test/tools/gen_vectors.py > test/host/vectors.h

Output is pure ASCII regardless of the payload contents, since every byte is
emitted in hex.
"""

import struct
import sys

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

try:
    from meshtastic.protobuf import mesh_pb2, portnums_pb2
except ImportError:  # older meshtastic package layout
    from meshtastic import mesh_pb2, portnums_pb2

# Channels.h:153-154 in meshtastic/firmware.
DEFAULT_PSK = bytes([
    0xd4, 0xf1, 0xbb, 0x3a, 0x20, 0x29, 0x07, 0x59,
    0xf0, 0xbc, 0xff, 0xab, 0xcf, 0x4e, 0x69, 0x01,
])


def expand_psk(index: int) -> bytes:
    """Channels.cpp:254-267. Index 1 means defaultpsk unchanged."""
    if index == 0:
        raise ValueError("index 0 means encryption disabled")
    key = bytearray(DEFAULT_PSK)
    key[-1] = (key[-1] + index - 1) & 0xFF
    return bytes(key)


def build_nonce(packet_id: int, from_node: int) -> bytes:
    """CryptoEngine::initNonce.

    8 bytes packet id little endian, 4 bytes source node little endian, then a
    4 byte block counter starting at zero.
    """
    return struct.pack("<QII", packet_id, from_node, 0)


def aes_ctr(key: bytes, nonce: bytes, data: bytes) -> bytes:
    encryptor = Cipher(algorithms.AES(key), modes.CTR(nonce)).encryptor()
    return encryptor.update(data) + encryptor.finalize()


def build_data(text: str) -> bytes:
    data = mesh_pb2.Data()
    data.portnum = portnums_pb2.PortNum.TEXT_MESSAGE_APP
    data.payload = text.encode("utf-8")
    return data.SerializeToString()


def xor_hash(b: bytes) -> int:
    h = 0
    for x in b:
        h ^= x
    return h


def channel_hash(name: str, key: bytes) -> int:
    """Channels::getHash. xorHash(name) XOR xorHash(key)."""
    return xor_hash(name.encode("utf-8")) ^ xor_hash(key)


def build_header(to, frm, packet_id, flags, chan_hash, next_hop, relay):
    """RadioInterface.h:36-53. Exactly 16 bytes, little endian."""
    header = struct.pack("<IIIBBBB", to, frm, packet_id, flags, chan_hash,
                         next_hop, relay)
    assert len(header) == 16, "PacketHeader must be exactly 16 bytes"
    return header


def c_bytes(name, data):
    """Emit a byte array.

    Empty arrays are emitted as a single zero because a zero-length array is
    not valid C99. The matching _LEN define carries the real length.
    """
    payload = data if data else b"\x00"
    body = ", ".join("0x%02x" % b for b in payload)
    return "static const uint8_t %s[] VEC_UNUSED = {%s};\n" % (name, body)


CASES = [
    # label, text, to, from, packet_id, hop_limit, hop_start, psk_index, channel
    ("simple", "hello mesh", 0xFFFFFFFF, 0x11223344, 0x0A0B0C0D, 3, 3, 1, "LongFast"),
    ("empty", "", 0xFFFFFFFF, 0x00000001, 0x00000001, 0, 0, 1, "LongFast"),
    ("long", "x" * 180, 0xFFFFFFFF, 0xDEADBEEF, 0xCAFEBABE, 7, 7, 1, "LongFast"),
    ("psk2", "second key", 0xFFFFFFFF, 0x0000ABCD, 0x00001234, 2, 3, 2, "LongFast"),
    ("utf8", "cafe ✓ éè", 0xFFFFFFFF, 0x55667788, 0x99AABBCC, 3, 3, 1, "LongFast"),
]


def main():
    out = sys.stdout
    out.write("/* Generated by test/tools/gen_vectors.py. Do not hand-edit. */\n")
    # Keep clang-format away from generated output. Without this the SDK
    # formatter rewrites the file and CI's regenerate-and-diff check fails
    # permanently, since the generator would never reproduce the formatted form.
    out.write("/* clang-format off */\n")
    out.write("#ifndef VECTORS_H\n#define VECTORS_H\n\n")
    out.write("#include <stdint.h>\n\n")
    out.write("/* Not every test uses every vector, and -Werror would reject\n"
              "   the unused ones. */\n")
    out.write("#if defined(__GNUC__)\n"
              "#define VEC_UNUSED __attribute__((unused))\n"
              "#else\n"
              "#define VEC_UNUSED\n"
              "#endif\n\n")
    out.write("#define VECTOR_COUNT %d\n\n" % len(CASES))

    for i, (label, text, to, frm, pid, hop_limit, hop_start, psk_index,
            chan_name) in enumerate(CASES):
        key = expand_psk(psk_index)
        nonce = build_nonce(pid, frm)
        plaintext = build_data(text)
        ciphertext = aes_ctr(key, nonce, plaintext)
        chash = channel_hash(chan_name, key)
        flags = (hop_limit & 0x07) | ((hop_start & 0x07) << 5)
        header = build_header(to, frm, pid, flags, chash, 0, 0)
        frame = header + ciphertext
        raw = text.encode("utf-8")

        p = "VEC%d_" % i
        out.write("/* case %d: %s */\n" % (i, label))
        out.write(c_bytes(p + "KEY", key))
        out.write("#define %sPACKET_ID 0x%08xu\n" % (p, pid))
        out.write("#define %sFROM_NODE 0x%08xu\n" % (p, frm))
        out.write("#define %sTO_NODE 0x%08xu\n" % (p, to))
        out.write("#define %sFLAGS 0x%02xu\n" % (p, flags))
        out.write("#define %sHOP_LIMIT %d\n" % (p, hop_limit))
        out.write("#define %sHOP_START %d\n" % (p, hop_start))
        out.write("#define %sCHANNEL_HASH 0x%02xu\n" % (p, chash))
        out.write("#define %sPORTNUM %d\n"
                  % (p, portnums_pb2.PortNum.TEXT_MESSAGE_APP))
        out.write(c_bytes(p + "NONCE", nonce))
        out.write(c_bytes(p + "PLAINTEXT", plaintext))
        out.write("#define %sPLAINTEXT_LEN %d\n" % (p, len(plaintext)))
        out.write(c_bytes(p + "CIPHERTEXT", ciphertext))
        out.write("#define %sCIPHERTEXT_LEN %d\n" % (p, len(ciphertext)))
        out.write(c_bytes(p + "FRAME", frame))
        out.write("#define %sFRAME_LEN %d\n" % (p, len(frame)))
        out.write(c_bytes(p + "TEXT", raw))
        out.write("#define %sTEXT_LEN %d\n\n" % (p, len(raw)))

    out.write("#endif\n")


if __name__ == "__main__":
    main()
